// Mock data for development mode

export const mockCrusades = [
  {
    id: 'crusade-1',
    name: 'Strength Training Challenge',
    type: 'fitness',
    description: 'Track your strength progress with bench press, deadlifts, squats, and more',
    icon: '💪',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'crusade-2',
    name: 'Bodyweight Warriors',
    type: 'fitness',
    description: 'Master bodyweight exercises like push-ups and pull-ups',
    icon: '🏋️',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'crusade-3',
    name: 'Meal Accountability',
    type: 'meal',
    description: 'Track your daily meals and stay accountable to your nutrition goals',
    icon: '🍽️',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'crusade-4',
    name: 'Daily Grind',
    type: 'daily',
    description: 'Log your daily workouts and build consistency',
    icon: '📅',
    is_active: true,
    created_at: new Date().toISOString(),
  },
]

export const mockEnrolledCrusades = [mockCrusades[0], mockCrusades[2]]

export const mockFitnessHistory = [
  {
    id: 'progress-1',
    user_id: 'dev-user-123',
    crusade_id: 'crusade-1',
    crusade_name: 'Strength Training Challenge',
    exercise_type: 'bench_press',
    weight_kg: 80,
    weight_lbs: 176,
    reps: 10,
    sets: 3,
    notes: 'Felt strong today!',
    photo_urls: '[]',
    x_post_url: 'https://x.com/example/123',
    created_at: new Date(Date.now() - 86400000).toISOString(), // 1 day ago
  },
  {
    id: 'progress-2',
    user_id: 'dev-user-123',
    crusade_id: 'crusade-1',
    crusade_name: 'Strength Training Challenge',
    exercise_type: 'squat',
    weight_kg: 100,
    weight_lbs: 220,
    reps: 8,
    sets: 4,
    notes: 'New PR! 🎉',
    photo_urls: '[]',
    created_at: new Date(Date.now() - 172800000).toISOString(), // 2 days ago
  },
  {
    id: 'progress-3',
    user_id: 'dev-user-123',
    crusade_id: 'crusade-2',
    crusade_name: 'Bodyweight Warriors',
    exercise_type: 'pullups',
    reps: 12,
    sets: 3,
    notes: 'Getting easier!',
    photo_urls: '[]',
    created_at: new Date(Date.now() - 259200000).toISOString(), // 3 days ago
  },
]

export const mockMealHistory = [
  {
    id: 'meal-1',
    user_id: 'dev-user-123',
    crusade_id: 'crusade-3',
    crusade_name: 'Meal Accountability',
    meal_type: 'breakfast',
    calories: 450,
    protein_g: 30,
    carbs_g: 40,
    fat_g: 15,
    food_items: 'Eggs, toast, avocado',
    notes: 'Great start to the day',
    photo_urls: '[]',
    created_at: new Date(Date.now() - 14400000).toISOString(), // 4 hours ago
  },
  {
    id: 'meal-2',
    user_id: 'dev-user-123',
    crusade_id: 'crusade-3',
    crusade_name: 'Meal Accountability',
    meal_type: 'lunch',
    calories: 650,
    protein_g: 45,
    carbs_g: 60,
    fat_g: 20,
    food_items: 'Grilled chicken, rice, vegetables',
    photo_urls: '[]',
    x_post_url: 'https://x.com/example/456',
    created_at: new Date(Date.now() - 86400000).toISOString(), // 1 day ago
  },
]

export const mockLeaderboard = [
  {
    user_id: 'user-1',
    discord_id: '111111',
    discord_username: 'FitnessKing',
    discord_avatar: null,
    x_username: 'fitnessking',
    workouts: 45,
    total_reps: 2850,
    score: 2850,
    entries: 45,
  },
  {
    user_id: 'user-2',
    discord_id: '222222',
    discord_username: 'IronWarrior',
    discord_avatar: null,
    x_username: 'ironwarrior',
    workouts: 38,
    total_reps: 2420,
    score: 2420,
    entries: 38,
  },
  {
    user_id: 'dev-user-123',
    discord_id: '123456789',
    discord_username: 'DevUser',
    discord_avatar: null,
    x_username: 'devuser',
    workouts: 28,
    total_reps: 1680,
    score: 1680,
    entries: 28,
  },
  {
    user_id: 'user-3',
    discord_id: '333333',
    discord_username: 'GymRat',
    discord_avatar: null,
    x_username: null,
    workouts: 25,
    total_reps: 1500,
    score: 1500,
    entries: 25,
  },
  {
    user_id: 'user-4',
    discord_id: '444444',
    discord_username: 'SwolePatrol',
    discord_avatar: null,
    x_username: 'swolepatrol',
    workouts: 22,
    total_reps: 1320,
    score: 1320,
    entries: 22,
  },
]

export const mockMealLeaderboard = [
  {
    user_id: 'user-5',
    discord_id: '555555',
    discord_username: 'NutritionNinja',
    discord_avatar: null,
    x_username: 'nutritionninja',
    meals: 84,
    total_calories: 126000,
    avg_calories: 1500,
  },
  {
    user_id: 'dev-user-123',
    discord_id: '123456789',
    discord_username: 'DevUser',
    discord_avatar: null,
    x_username: 'devuser',
    meals: 56,
    total_calories: 89600,
    avg_calories: 1600,
  },
  {
    user_id: 'user-6',
    discord_id: '666666',
    discord_username: 'MealPrepper',
    discord_avatar: null,
    x_username: null,
    meals: 42,
    total_calories: 67200,
    avg_calories: 1600,
  },
]