name = "vvv-crusade-tracker-api"
main = "src/index.js"
compatibility_date = "2023-12-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[[d1_databases]]
binding = "DB"
database_name = "vvv-crusade-tracker"
database_id = "YOUR_DATABASE_ID"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "vvv-crusade-photos"

[vars]
JWT_SECRET = "your-jwt-secret-here"
DISCORD_CLIENT_ID = "your-discord-client-id"
DISCORD_CLIENT_SECRET = "your-discord-client-secret"
DISCORD_REDIRECT_URI = "http://localhost:3000/api/auth/discord/callback"
X_CONSUMER_KEY = "your-x-consumer-key"
X_CONSUMER_SECRET = "your-x-consumer-secret"
FRONTEND_URL = "http://localhost:3000"